### ISSUE TITLE
Cleancss is missing : impossible to run

### ISSUE THREAD

**Issue by Epholys** [jobtalle/Koi#181]
Hello,

I am on Linux after cloning and pulling submodule, I tried running `npm run build-linux-64` but npm throw an error during execution of `squish.py`:

```
> koifarm@1.0.0 build-linux-64 /home/epholys/src/koi
> npm run compress && electron-packager . KoiFarm --platform=linux --arch=x64 --icon=./favicon.ico --appCopyright="Copyright Job Talle 2021" --ignore="^/js|^/css|^/squish\.py|^/node_modules|^/\.idea|index\.html|README\.md|favicon\.icns|LICENSE|package-lock\.json"


> koifarm@1.0.0 compress /home/epholys/src/koi
> python3 squish.py/squish.py index.html release.html

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/cleancss - Not found
npm ERR! 404 
npm ERR! 404  'cleancss@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/epholys/.npm/_logs/2021-04-01T12_25_13_773Z-debug.log
Install for cleancss@latest failed with code 1
Traceback (most recent call last):
  File "squish.py/squish.py", line 205, in <module>
    Document(args['source']).process(args['target'], sys.argv)
  File "squish.py/squish.py", line 33, in process
    self.__collect((
  File "squish.py/squish.py", line 193, in __collect
    self.__extract_tags([tag[0] for tag in tags], get_match)
  File "squish.py/squish.py", line 126, in __extract_tags
    self.__source = re.sub(self.__make_regex_tag(tags), match, self.__source)
  File "/usr/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "squish.py/squish.py", line 189, in get_match
    self.__compress(directory, combined[tag], include_tag[tag], css_variables, flags))
  File "squish.py/squish.py", line 57, in __compress
    return compress_css(contents, css_variables)
  File "/home/epholys/src/koi/squish.py/css.py", line 57, in compress_css
    with open('tmp-out', 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp-out'

[END OF LOG OMMITED]
```

Am I doing something wrong or is there something wrong with the registry?

Thank you for making your game open-source!

**Comment by jobtalle** [comment]
Cleancss should be installed when running `npm i` according to `package.json`: https://github.com/jobtalle/Koi/blob/master/package.json

Did you install dependencies correctly?

**Comment by Epholys** [comment]
Oh, I've skimmed through the readme a little too quickly and forget the `npm i` step... It works perfectly now.

Sorry for the dumb issue, thank you for the help
